## 0. Load imports

In [2]:
## imports
import pandas as pd
import numpy as np


## print multiple things from same cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## 0. Load data

In [3]:
## load data on 2020 crimes in DC
df = dc_crim_2020 = pd.read_csv("https://opendata.arcgis.com/datasets/f516e0dd7b614b088ad781b0c4002331_2.csv")
dc_crim_2020.head()
dc_crim_2020.shape
dc_crim_2020.info()

,X,Y,CCN,REPORT_DAT,START_DATE,END_DATE,BLOCK,OFFENSE,METHOD,SHIFT,...,BLOCK_GROUP,CENSUS_TRACT,VOTING_PRECINCT,BID,XBLOCK,YBLOCK,LATITUDE,LONGITUDE,OBJECTID,OCTO_RECORD_ID
0,400038.00,137846.00,20087784,2020/06/14 05:40:24+00,2020/05/15 22:30:29+00,2020/06/13 21:45:00+00,1250 - 1299 BLOCK OF 4TH STREET NE,THEFT/OTHER,OTHERS,MIDNIGHT,...,008803 2,8803.0,Precinct 76,NaN,400038.00,137846.00,38.908474,-76.999562,981490694,NaN
1,402228.00,133997.00,20400905,2020/07/06 17:06:08+00,2020/07/02 10:00:00+00,2020/07/02 11:00:00+00,2200 - 2299 BLOCK OF NICHOLSON STREET SE,THEFT F/AUTO,OTHERS,DAY,...,007601 1,7601.0,Precinct 111,NaN,402228.00,133997.00,38.873798,-76.974325,981490695,NaN
2,400384.00,136370.00,20401461,2020/09/22 17:28:57+00,2020/09/19 17:15:00+00,2020/09/20 17:15:00+00,700 - 799 BLOCK OF MARYLAND AVENUE NE,THEFT F/AUTO,OTHERS,DAY,...,008302 1,8302.0,Precinct 84,NaN,400384.00,136370.00,38.895178,-76.995573,981490696,NaN
3,397577.00,143785.00,20013614,2020/01/23 19:00:33+00,2020/01/23 15:31:11+00,2020/01/23 16:03:42+00,5900 - 5999 BLOCK OF GEORGIA AVENUE NW,MOTOR VEHICLE THEFT,OTHERS,DAY,...,001901 1,1901.0,Precinct 58,NaN,397577.00,143785.00,38.961971,-77.027957,981491195,NaN
4,397855.87,140120.06,20013926,2020/01/24 01:32:43+00,2020/01/23 14:00:43+00,2020/01/23 22:05:57+00,700 - 999 BLOCK OF IRVING STREET NW,BURGLARY,OTHERS,EVENING,...,003100 1,3100.0,Precinct 38,NaN,397855.87,140120.06,38.928957,-77.024728,981491196,NaN

(27932, 25)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27932 entries, 0 to 27931
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   X                     27932 non-null  float64
 1   Y                     27932 non-null  float64
 2   CCN                   27932 non-null  int64
 3   REPORT_DAT            27932 non-null  object
 4   START_DATE            27932 non-null  object
 5   END_DATE              24851 non-null  object
 6   BLOCK                 27932 non-null  object
 7   OFFENSE               27932 non-null  object
 8   METHOD                27932 non-null  object
 9   SHIFT                 27932 non-null  object
 10  WARD                  27932 non-null  int64
 11  ANC                   27932 non-null  object
 12  DISTRICT              27903 non-null  float64
 13  PSA                   27897 non-null  float64
 14  NEIGHBORHOOD_CLUSTER  27932 non-null  object
 15  BLOCK_GROUP           27931 non-null  object
 16  CENSUS_TRACT          27931 non-null  float64
 17  VOTING_PRECINCT       27932 non-null  object
 18  BID                   4658 non-null   object
 19  XBLOCK                27932 non-null  float64
 20  YBLOCK                27932 non-null  float64
 21  LATITUDE              27932 non-null  float64
 22  LONGITUDE             27932 non-null  float64
 23  OBJECTID              27932 non-null  int64
 24  OCTO_RECORD_ID        0 non-null      float64
dtypes: float64(10), int64(3), object(12)
memory usage: 5.3+ MB

#### Warm-up: Ways to add 100 to column X

In [4]:
%%time
df.X + 100

CPU times: user 128 μs, sys: 114 μs, total: 242 μs
Wall time: 236 μs

0        396317.89
1        400694.00
2        404164.01
3        403440.00
4        398065.00
           ...
27927    406551.00
27928    397328.00
27929    400694.00
27930    394435.00
27931    397923.00
Name: X, Length: 27932, dtype: float64

In [5]:
%%time
nums_plus_100 = []
for x in df["X"]:
    x_100 = x+100
    nums_plus_100.append(x_100)

CPU times: user 7.74 ms, sys: 1.6 ms, total: 9.34 ms
Wall time: 8.43 ms

## 1. Aggregation

### Example of grouping by one variable and doing one aggregation 

**Task**: find and print the number of unique offense types (`OFFENSE`) by ward (`WARD`)

In [6]:
answer = df.groupby('WARD')['OFFENSE'].nunique()
print(answer)

WARD
1    9
2    9
3    8
4    8
5    9
6    9
7    9
8    9
Name: OFFENSE, dtype: int64

### Example of grouping by one variable and providing two summaries of the same variable

**Task**: previous showed number of offenses by ward but want to find out content of offenses in each ward; create an aggregation that summarizes both the number of unique offenses by ward and what those offenses are -- for instance, by pasting the unique offenses in that ward separated by the ";" (e.g., Theft; Burglary;...)

*Hint*: you can use the join command to paste together a list separated by some delimiter. 
    - The syntax, if we are using the comma delimiter, is: ", ".join(nameoflist)

In [8]:
answer = df.groupby('WARD')['OFFENSE'].agg(
    num_unique_offenses='nunique',
    offense_types=lambda x: '; '.join(x.unique()))

print(answer)

      num_unique_offenses                                      offense_types
WARD
1                       9  THEFT F/AUTO; THEFT/OTHER; MOTOR VEHICLE THEFT...
2                       9  BURGLARY; THEFT/OTHER; THEFT F/AUTO; ASSAULT W...
3                       8  THEFT/OTHER; THEFT F/AUTO; MOTOR VEHICLE THEFT...
4                       8  THEFT F/AUTO; THEFT/OTHER; ROBBERY; BURGLARY; ...
5                       9  THEFT/OTHER; THEFT F/AUTO; ROBBERY; ASSAULT W/...
6                       9  THEFT/OTHER; ROBBERY; THEFT F/AUTO; BURGLARY; ...
7                       9  THEFT F/AUTO; ROBBERY; THEFT/OTHER; MOTOR VEHI...
8                       9  MOTOR VEHICLE THEFT; THEFT/OTHER; ASSAULT W/DA...

### Example of grouping by two variables 

**Task**: group by ward (`WARD`) and police shift (`SHIFT`) and find the offense that is most common in that ward and shift

In [9]:
def most_common_offense(x):
    return x.mode()[0]
result = df.groupby(['WARD', 'SHIFT'])['OFFENSE'].agg(most_common_offense)
print(result)

WARD  SHIFT
1     DAY                        THEFT/OTHER
      EVENING                    THEFT/OTHER
      MIDNIGHT                   THEFT/OTHER
2     DAY                        THEFT/OTHER
      EVENING                    THEFT/OTHER
      MIDNIGHT                   THEFT/OTHER
3     DAY                        THEFT/OTHER
      EVENING                    THEFT/OTHER
      MIDNIGHT                   THEFT/OTHER
4     DAY                       THEFT F/AUTO
      EVENING                    THEFT/OTHER
      MIDNIGHT                   THEFT/OTHER
5     DAY                       THEFT F/AUTO
      EVENING                    THEFT/OTHER
      MIDNIGHT                   THEFT/OTHER
6     DAY                        THEFT/OTHER
      EVENING                    THEFT/OTHER
      MIDNIGHT                   THEFT/OTHER
7     DAY                       THEFT F/AUTO
      EVENING                    THEFT/OTHER
      MIDNIGHT                   THEFT/OTHER
8     DAY                       THEFT F/AUTO
      EVENING                    THEFT/OTHER
      MIDNIGHT    ASSAULT W/DANGEROUS WEAPON
Name: OFFENSE, dtype: object

## Summarizing over all rows or all columns (without grouping)

We can also use the `apply` function to summarize rows or columns efficiently

**Task**: find the mean lat and longitude in one line of code

In [10]:
print(df[["X", "Y"]].apply("mean"))

X    399389.539270
Y    137750.842027
dtype: float64

## 2. Creating new columns/transforming their type

### Simple filtering

`np.where` is in the numpy package (aliased as `np`) and operates similar to `ifelse` in R

But there is a built in pandas way to emulate this.

**Task**: create an indicator `is_theft` for any offense that contains the word "THEFT"
    
**Task**: create an indicator `is_theft_notmotor` for any offense that contains the word "THEFT" but does not contain the word "MOTOR"

In [16]:
df["is_theft"] = df.OFFENSE.str.contains("THEFT")
df["is_theft_notmotor"] = (df.OFFENSE.str.contains("THEFT") & ~df.OFFENSE.str.contains("MOTOR"))
print(df.is_theft)

0        False
1         True
2         True
3         True
4         True
         ...
27927     True
27928     True
27929    False
27930     True
27931     True
Name: is_theft, Length: 27932, dtype: bool

### np.select

**Task**: create a new variable, `offense_summary`, where you:
        
- Recode theft offenses that use a gun or knife as the method (`METHOD`) as: violent theft
- Recode non-theft offenses that use a gun or knife as the method as: violent other
- Recode all other as non-violent

In [12]:
category = ["violent theft", "violent other"]
df["is_theft"] = df.OFFENSE.str.contains("THEFT")
conditions = [df.is_theft & df.METHOD.isin(["gun", "knife"]),
    ~df.is_theft & df.METHOD.isin(["gun", "knife"])]
df["offense_summary"] = np.select(conditions, category, default="non-violent")

,X,Y,CCN,REPORT_DAT,START_DATE,END_DATE,BLOCK,OFFENSE,METHOD,SHIFT,...,BID,XBLOCK,YBLOCK,LATITUDE,LONGITUDE,OBJECTID,OCTO_RECORD_ID,is_theft,is_theft_notmotor,offense_summary
0,396217.89,138008.23,20143189,2020/10/07 05:06:33+00,2020/10/05 20:00:29+00,2020/10/07 03:11:00+00,1300 - 1699 BLOCK OF CONNECTICUT AVENUE NW,BURGLARY,OTHERS,MIDNIGHT,...,DUPONT CIRCLE,396217.89,138008.23,38.909927,-77.043607,976657932,NaN,False,False,non-violent
1,400594.00,139371.00,20019634,2020/02/02 00:38:51+00,2020/02/01 22:30:56+00,2020/02/01 23:14:15+00,900 - 999 BLOCK OF RHODE ISLAND AVENUE NE,THEFT/OTHER,OTHERS,EVENING,...,NaN,400594.00,139371.00,38.922212,-76.993150,976657941,NaN,True,True,non-violent
2,404064.01,139635.98,20022515,2020/02/06 19:38:30+00,2020/02/05 23:00:07+00,2020/02/06 19:48:32+00,3600 - 3799 BLOCK OF JAMISON STREET NE,THEFT F/AUTO,OTHERS,DAY,...,NaN,404064.01,139635.98,38.924589,-76.953133,976657942,NaN,True,True,non-violent
3,403340.00,132117.00,20085996,2020/06/10 17:01:07+00,2020/06/09 23:30:29+00,2020/06/10 10:50:38+00,2700 - 2799 BLOCK OF 32ND STREET SE,THEFT F/AUTO,OTHERS,DAY,...,NaN,403340.00,132117.00,38.856859,-76.961519,976657945,NaN,True,True,non-violent
4,397965.00,138634.00,20044480,2020/03/13 07:42:44+00,2020/03/13 07:07:01+00,NaN,800 - 899 BLOCK OF T STREET NW,THEFT F/AUTO,OTHERS,MIDNIGHT,...,NaN,397965.00,138634.00,38.915570,-77.023465,976657959,NaN,True,True,non-violent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27927,406451.00,137312.00,20130009,2020/09/11 21:11:46+00,2020/09/11 18:01:25+00,2020/09/11 19:30:49+00,5100 - 5199 BLOCK OF SHERIFF ROAD NE,THEFT F/AUTO,OTHERS,EVENING,...,NaN,406451.00,137312.00,38.903640,-76.925628,977253793,NaN,True,True,non-violent
27928,397228.00,138674.00,20132175,2020/09/15 22:59:16+00,2020/09/14 04:00:11+00,2020/09/14 06:00:27+00,1900 - 1920 BLOCK OF 14TH STREET NW,THEFT/OTHER,OTHERS,EVENING,...,NaN,397228.00,138674.00,38.915929,-77.031963,977253794,NaN,True,True,non-violent
27929,400594.00,139371.00,20123057,2020/08/28 21:31:45+00,2020/08/28 20:26:16+00,2020/08/28 20:40:53+00,900 - 999 BLOCK OF RHODE ISLAND AVENUE NE,ROBBERY,GUN,EVENING,...,NaN,400594.00,139371.00,38.922212,-76.993150,977253796,NaN,False,False,non-violent
27930,394335.00,142159.00,20018868,2020/01/31 19:36:51+00,2019/12/14 17:00:23+00,2020/01/31 19:37:12+00,4400 - 4499 BLOCK OF CONNECTICUT AVENUE NW,MOTOR VEHICLE THEFT,OTHERS,DAY,...,NaN,394335.00,142159.00,38.947309,-77.065351,977253826,NaN,True,False,non-violent
27931,397823.00,141376.00,20150775,2020/10/21 21:01:34+00,2020/10/21 05:30:40+00,2020/10/21 05:32:41+00,4000 - 4099 BLOCK OF GEORGIA AVENUE NW,THEFT/OTHER,OTHERS,EVENING,...,NaN,397823.00,141376.00,38.940271,-77.025111,977253835,NaN,True,True,non-violent

### map.recode

**Task**: recode shifts that are MIDNIGHT or EVENING as "nighttime"; code other shift to daytime

In [44]:
condition = [df.SHIFT.isin(["MIDNIGHT", "EVENING"])]
category = ["nighttime"]
df["time_day"] = np.select(condition, category, default="daytime")

### Using built-in pandas methods

Another way of creating variables, used either alone or in combination with np.where and np.select is to use pandas built in `str` methods

Basic structure is: `df['namestringcol'].str.someoperation`

**Task**: using a `str` method, create a new column--`OFFENSE_NOSP`--that replaces spaces in the `OFFENSE` column with underscores

In [25]:
df["OFFENSE_NOSP"] = df.OFFENSE.str.replace(" ", "_")

### Transforming column types

**Task**: check the type of the `START_DATE` column

In [6]:
df.START_DATE.iloc[0]

2020/05/15 22:30:29+00

**Task**: recast the `START_DATE` column to datetime, calling this `START_DATE_CLEAN`; coerce errors rather than cleaning the string; check the type of that new col

In [37]:
df["START_DATE_CLEAN"] = pd.to_datetime(df.START_DATE)

**Task:** print the min and max of `START_DATE_CLEAN`. What happens if you try to do this with `START_DATE`?

In [40]:
df["START_DATE_CLEAN"].min(), df["START_DATE_CLEAN"].max()

(Timestamp('1940-02-17 00:00:16+0000', tz='UTC'),
 Timestamp('2021-01-01 02:30:21+0000', tz='UTC'))

In [41]:
df["START_DATE"].min(), df["START_DATE"].max()

('1940/02/17 00:00:16+00', '2021/01/01 02:30:21+00')

## 3. Row and column filtering

### Row subsetting

**Task**: filter to crime reports about theft using the `is_theft` definition and that are in ward 3

In [1]:
rows = df[(df.is_theft) & (df.WARD==3)]
print(rows)

NameError: name 'df' is not defined

### Column subsetting

**Task**: select two columns--`START_DATE` and `END_DATE`--and print the head of the dataframe

In [21]:
columns = df[["START_DATE", "END_DATE"]]
print(columns.head())

               START_DATE                END_DATE
0  2020/10/05 20:00:29+00  2020/10/07 03:11:00+00
1  2020/02/01 22:30:56+00  2020/02/01 23:14:15+00
2  2020/02/05 23:00:07+00  2020/02/06 19:48:32+00
3  2020/06/09 23:30:29+00  2020/06/10 10:50:38+00
4  2020/03/13 07:07:01+00                     NaN

**Task**: use list comprehension to automate this a bit and select all columns with the word "DATE" in the name; print the head of the dataframe

In [24]:
comp = [columns for columns in df.columns if "DATE" in columns]
print(columns.head())

               START_DATE                END_DATE
0  2020/10/05 20:00:29+00  2020/10/07 03:11:00+00
1  2020/02/01 22:30:56+00  2020/02/01 23:14:15+00
2  2020/02/05 23:00:07+00  2020/02/06 19:48:32+00
3  2020/06/09 23:30:29+00  2020/06/10 10:50:38+00
4  2020/03/13 07:07:01+00                     NaN

**Task**: filter reports of crime in `START_DATE_CLEAN` before May 2020 and that are located in ward 1; select the ward and `START_DATE` column and print a random sample of rows

In [50]:
df[(df.START_DATE_CLEAN < "2020-05-01") & (df["WARD"] == 1)][["WARD", "START_DATE"]].sample(5)

       WARD              START_DATE
25172     1  2020/02/16 23:00:43+00
19761     1  2020/01/07 17:00:00+00
18343     1  2020/02/21 22:29:03+00
934       1  2020/01/11 21:15:05+00
23167     1  2020/02/10 03:00:34+00